name: Run self

on:
  # Run on all PRs
  pull_request:
    paths-ignore:
      - "**.md"
  # Run when a PR is merged into main
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  run-self:
    name: Run self
    strategy:
      matrix:
        operating-systems:
          - ubuntu-latest
          # - macos-latest # TODO: Re-enable one day
        testing:
          - always
          - never
          - auto
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Run the action
        uses: ./
        with:
          testing: ${{ matrix.testing }}
      - name: Make sure Roc is installed
        run: roc --version
