name: Run self

on:
  # Run on all PRs
  pull_request:
    paths-ignore:
      - "**.md"
  # Run when a PR is merged into main
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  run-self:
    name: Run self
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: install z3 on MacOS
        if: runner.os == 'macOS'
        run: brew install z3
      - name: Run the action
        uses: ./
      - name: Make sure Roc is installed
        run: roc --version
